src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comments
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(name: 'user_id', nullable: false)]
    private ?Users $user = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(name: 'ticket_id', referencedColumnName: 'id', nullable: false)]
    private ?Tickets $ticket = null;

    /**
     * @var Collection<int, Images>
     */
    #[ORM\OneToMany(targetEntity: Images::class, mappedBy: 'comment', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setComment($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getComment() === $this) {
                $image->setComment(null);
            }
        }

        return $this;
    }

    public function getTicket(): ?Tickets
    {
        return $this->ticket;
    }

    public function setTicket(?Tickets $ticket): static
    {
        $this->ticket = $ticket;
        return $this;
    }
}

src/Entity/Tickets.php
<?php

namespace App\Entity;

use App\Enum\Stacks;
use App\Repository\TicketsRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TicketsRepository::class)]
class Tickets
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?DateTimeImmutable $created_at = null;

    #[ORM\PrePersist]
    public function setCreatedAtValue()
    {
        if($this->created_at === null){
            $this->created_at = new DateTimeImmutable();
        }
    }

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Status $status = null;

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(name: 'user_id', nullable: false)]
    private ?Users $user = null;

    #[ORM\Column(enumType: Stacks::class)]
    private ?Stacks $stack = null;

    #[ORM\Column(enumType: Types::class)]
    private ?\App\Enum\Types $type = null;

    // #[ORM\ManyToOne(inversedBy: 'ticket')]
    // private ?Comments $comments = null;

    /**
     * @var Collection<int, Comments>
     */

    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'ticket', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $comments;

    /**
     * @var Collection<int, Images>
     */
    #[ORM\OneToMany(targetEntity: Images::class, mappedBy: 'ticket', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getStack(): ?Stacks
    {
        return $this->stack;
    }

    public function setStack(Stacks $stack): static
    {
        $this->stack = $stack;

        return $this;
    }

    public function getType(): ?\App\Enum\Types
    {
        return $this->type;
    }

    public function setType(\App\Enum\Types $type): static
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */

    public function getComments(): ?Collection
    {
        return $this->comments;
    }

    public function addComment(?Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTicket($this);
        }
        return $this;
    }
    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getTicket() === $this) {
                $comment->setTicket(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setTicket($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTicket() === $this) {
                $image->setTicket(null);
            }
        }

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

// use App\Repository\RolesRepository;
use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'This email is already in use.')]
#[UniqueEntity(fields: ['nickname'], message: 'This nickname is already taken.')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nickname = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 60)]
    private ?string $password = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Roles $role = null;

    /**
     * @var Collection<int, Tickets>
     */
    #[ORM\OneToMany(targetEntity: Tickets::class, mappedBy: 'user')]
    private Collection $tickets;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'user')]
    private Collection $comments;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $avatar = null;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): static
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?Roles
    {
        return $this->role;
    }

    public function setRole(?Roles $role): static
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return Collection<int, Tickets>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Tickets $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setUser($this);
        }

        return $this;
    }

    public function removeTicket(Tickets $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getUser() === $this) {
                $ticket->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roleTitle = strtolower($this->role?->getTitle() ?? 'user');

        $roleMapping = [
            'user' => 'ROLE_USER',
            'admin' => 'ROLE_ADMIN',
        ];

        return [$roleMapping[$roleTitle] ?? 'ROLE_USER'];
    }

    public function eraseCredentials(): void
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }
}

src/Form/TicketsType.php
<?php

namespace App\Form;

use App\Entity\Tickets;
use App\Enum\Stacks;
use App\Enum\Types;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\File;

class TicketsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Subject : ',
                'required' => true,
                'attr' => [
                    'placeholder' => 'Describe the subject of the ticket ...'
                ]
            ])            
            ->add('stack', EnumType::class, [
                'label' => 'Technology : ',
                'required' => true,
                'class' => Stacks::class,
                'choice_label' => fn(Stacks $e) => $e->value,
                'placeholder' => 'Choose a technology',
                'expanded' => false,
                'multiple' => false
            ])
            ->add('type', EnumType::class, [
                'label' => 'Category : ',
                'required' => true,
                'class' => Types::class,
                'choice_label' => fn(Types $e) => $e->value,
                'placeholder' => 'Choose a category',
                'expanded' => false,
                'multiple' => false
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Description : ',
                'required' => false,
                'constraints' => [
                    new NotBlank(message: 'Please write a description.'),
                ],
                'attr' => [
                    'class' => 'js-ckeditor',
                    
                ]
            ])
            ->add('imageFiles', FileType::class, [
                'label' => 'Attach images (JPG, PNG, max 5MB) :',
                'mapped' => false,
                'required' => false,
                'multiple' => true,
                'constraints' => [
                    new All([
                        new File([
                            'maxSize' => '5M',
                            'mimeTypes' => [
                                'image/jpeg',
                                'image/png',
                                'image/webp',
                            ],
                            'mimeTypesMessage' => 'Please upload a valid image (JPG, PNG or WebP)',
                        ])
                    ])
                ],
                'attr' => [
                    'accept' => 'image/*'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tickets::class,
        ]);
    }
}

templates/tickets/_delete_form.html.twig
<form method="post" action="{{ path('app_tickets_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tickets/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {# <link rel="stylesheet" href="{{ asset('styles/tickets.css') }}"> #}
{% endblock %}

{% block title %}BT Crack{% endblock %}

{% block body %}
    <section class="tickets-section">
        <form class="tickets-filter-form" action="{{ path('app_tickets_index') }}" method="GET">
            <select name="type" id="type" onchange="this.form.submit()">
                <option value="">Type (all)</option>
                {% for t in types %}
                    <option value="{{ t.value }}" {{ filters.type == t.value ? 'selected' }}>
                        {{ t.value }}
                    </option>
                {% endfor %}
            </select>
            <input type="hidden" name="stack" value="{{ filters.stack }}">
            <input type="hidden" name="status" value="{{ filters.status }}">
            <input type="hidden" name="search" value="{{ filters.search }}">
        </form>
        <form class="tickets-filter-form" action="{{ path('app_tickets_index') }}" method="GET">
            <select name="stack" id="stack" onchange="this.form.submit()">
                <option value="">Technology (all)</option>
                {% for s in stacks %}
                    <option value="{{ s.value }}" {{ filters.stack == s.value ? 'selected' }}>
                        {{ s.value }}
                    </option>
                {% endfor %}
            </select>
            <input type="hidden" name="type" value="{{ filters.type }}">
            <input type="hidden" name="status" value="{{ filters.status }}">
            <input type="hidden" name="search" value="{{ filters.search }}">
        </form>
        <form class="tickets-filter-form" action="{{ path('app_tickets_index') }}" method="GET">
            <select name="status" id="status" onchange="this.form.submit()">
                <option value="">Status (all)</option>
                {% for s in status %}
                    <option value="{{ s.value }}" {{ filters.status == s.value ? 'selected' }}>
                        {{ s.value }}
                    </option>
                {% endfor %}
            </select>
            <input type="hidden" name="type" value="{{ filters.type }}">
            <input type="hidden" name="stack" value="{{ filters.stack }}">
            <input type="hidden" name="search" value="{{ filters.search }}">
        </form>
        <form class="tickets-search-form" action="{{ path('app_tickets_index') }}" method="GET">
            <input type="text" name="search" placeholder="Search tickets" value="{{ filters.search }}">
            <button class="btn btn-primary" type="submit">Search</button>
            <input type="hidden" name="type" value="{{ filters.type }}">
            <input type="hidden" name="stack" value="{{ filters.stack }}">
            <input type="hidden" name="status" value="{{ filters.status }}">
        </form>
        {% if filters.type or filters.stack or filters.status or filters.search %}
            <a href="{{ path('app_tickets_index') }}" class="btn btn-secondary">
                Reset filters
            </a>
        {% endif %}
    </section>

    <section class="tickets-list">
        <h1>Tickets List</h1>
        
        {% if tickets|length > 0 %}
            <div class="tickets-container">
                {% for ticket in tickets %}
                    <div class="ticket-card">
                        <div class="ticket-card-header">
                            <h2>
                                <a href="{{ path('app_tickets_show', {'id': ticket.id}) }}">
                                    {{ ticket.title }}
                                </a>
                            </h2>
                            <span class="ticket-id">#{{ ticket.id }}</span>
                        </div>
                        
                        <div class="ticket-card-meta">
                            <span class="badge badge-status">{{ ticket.status.status.value }}</span>
                            <span class="badge badge-type">{{ ticket.type.value }}</span>
                            <span class="badge badge-stack">{{ ticket.stack.value }}</span>
                        </div>
                        
                        {# <div class="ticket-card-content">
                            <h3>Description :</h3>
                            <p>{{ticket.content|length > 200 ? ticket.content|slice(0, 200) ~ '...' : ticket.content }}</p>
                        </div> #}
                        
                        <div class="ticket-card-footer">
                            <div class="ticket-author">
                                <strong>Created by:</strong> 
                                {{ ticket.user.firstName }} {{ ticket.user.lastName }}
                            </div>
                            <div class="ticket-date">
                                <strong>On:</strong> 
                                {{ ticket.createdAt|date('d/m/Y à H:i') }}
                            </div>
                        </div>
                        
                        <div class="ticket-card-actions">
                            <a href="{{ path('app_tickets_show', {'id': ticket.id}) }}" class="btn-tickets ">View details</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="no-tickets">No tickets have been created yet.</p>
        {% endif %}
    </section>

    <section class="pagination-section">    
        {% if totalPages > 1 %}
            <nav class="pagination-nav" aria-label="Pagination">
                <ul class="pagination">
                    {% if currentPage > 1 %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path('app_tickets_index', filters|merge({'page': currentPage - 1})) }}">
                                &laquo; Previous
                            </a>
                        </li>
                    {% endif %}
                    {% for page in 1..totalPages %}
                        {% if page == currentPage %}
                            <li class="page-item active">
                                <span class="page-link">{{ page }}</span>
                            </li>
                        {% elseif page >= currentPage - 2 and page <= currentPage + 2 %}
                            <li class="page-item">
                                <a class="page-link" href="{{ path('app_tickets_index', filters|merge({'page': page})) }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if currentPage < totalPages %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path('app_tickets_index', filters|merge({'page': currentPage + 1})) }}">
                                Next &raquo;
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </section>


{% endblock %}

templates/tickets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ticket.title }} - Ticket #{{ ticket.id }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {# <link rel="stylesheet" href="{{ asset('styles/ticket-show.css') }}"> #}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('upload_img.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const form = document.querySelector('.add-comment-form form');
            if (form) {
                form.addEventListener('submit', function(e) {
                    // Forcer la synchronisation de tous les CKEditor avant soumission
                    document.querySelectorAll('.ck-editor').forEach((editorElement) => {
                        const textarea = editorElement.previousElementSibling;
                        if (textarea && textarea.tagName === 'TEXTAREA') {
                            const editorInstance = textarea.ckeditorInstance;
                            if (editorInstance) {
                                textarea.value = editorInstance.getData();
                            }
                        }
                    });
                });
            }
        });
    </script>
{% endblock %}

{% block body %}
    <div class="ticket-show-container">
        {# Flash messages #}
        {% for label, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ label }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}

        {# Navigation #}
        <div class="ticket-navigation">
            <a href="{{ path('app_tickets_index') }}">← Back to list</a>
        </div>

        {# Ticket header #}
        <div class="ticket-header">
            <h1>{{ ticket.title }}</h1>
            <div class="ticket-meta">
                <span class="ticket-id">Ticket #{{ ticket.id }}</span>
                <span class="ticket-status">Status: {{ ticket.status.status.value }}</span>
                <span class="ticket-type">Type: {{ ticket.type.value }}</span>
                <span class="ticket-stack">Stack: {{ ticket.stack.value }}</span>
            </div>
        </div>

        {# Main information #}
        <div class="ticket-main">
            <div class="ticket-content">
                <h2>Description</h2>
                <div class="content-text">
                    {{ ticket.content|raw }}
                </div>
            </div>

            <div class="ticket-info">
                <h3>Information</h3>
                <dl>
                    <dt>Created on:</dt>
                    <dd>{{ ticket.createdAt|date('d/m/Y à H:i') }}</dd>
                    
                    <dt>Created by:</dt>
                    <dd>
                        {{ ticket.user.firstName }} {{ ticket.user.lastName }} 
                        ({{ ticket.user.nickname }})
                    </dd>
                    
                    <dt>Email:</dt>
                    <dd>{{ ticket.user.email }}</dd>
                </dl>
            </div>
        </div>

        {# Attached images #}
        {% if ticket.images|length > 0 %}
            <div class="ticket-images">
                <h2>Attached images ({{ ticket.images|length }})</h2>
                <div class="images-grid">
                    {% for image in ticket.images %}
                        <div class="image-item">
                            <img src="{{ asset(image.url) }}" alt="Ticket image" class="clickable-image" title="Click to enlarge">
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {# Comments section #}
        <div class="ticket-comments">
            <h2>Comments ({{ ticket.comments|length }})</h2>
            
            {% if ticket.comments|length > 0 %}
                <div class="comments-list">
                    {% for comment in ticket.comments %}
                        <div class="comment-item">
                            <div class="comment-header">
                                <strong>{{ comment.user.firstName }} {{ comment.user.lastName }}</strong>
                                <span class="comment-date">{{ comment.createdAt|date('d/m/Y à H:i') }}</span>
                                {% if comment.updatedAt %}
                                    <span class="comment-edited">(edited on {{ comment.updatedAt|date('d/m/Y à H:i') }})</span>
                                {% endif %}
                            </div>
                            <div class="comment-content">
                                {{ comment.content|raw }}
                            </div>
                            
                            {# Comment images #}
                            {% if comment.images|length > 0 %}
                                <div class="comment-images">
                                    {% for image in comment.images %}
                                        <img src="{{ asset(image.url) }}" alt="Comment image" class="clickable-image" title="Click to enlarge" style="max-width: 200px; cursor: pointer;">
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>No comments yet.</p>
            {% endif %}
            
            {# Add comment form #}
            {# <div>
                {{dump(ticket.getStatus().id)}}
            </div> #}
            {% if ticket.getStatus().id == 1 or ticket.getStatus().id == 2 %}
            
                <div class="add-comment-form">
                    {% if app.user %}
                        <h3>Add a comment</h3>
                        {# attr novalidate to disable HTML5 validation, it disables the validation of fields that are "required" by default #}
                        {{ form_start(commentForm, {'attr': {'novalidate': 'novalidate', 'data-turbo': 'false'}}) }}
                            {{ form_errors(commentForm) }}
                            {{ form_row(commentForm.content) }}
                            {{ form_row(commentForm.imageFiles) }}
                            <button type="submit" class="btn btn-primary">+ Add a comment</button>
                        {{ form_end(commentForm) }}
                    {% else %}
                        <a href="{{ path('app_login') }}"><button>Log in to add a comment.</button></a>
                    {% endif %}
                </div>
            
            {% else %}
                <h2>
                    Ticket Closed
                </h2>
            {% endif %}
            
            
        </div>

        {# Actions #}
        {% if is_granted('TICKET_UPDATE_STATUS', ticket) or is_granted('TICKET_DELETE', ticket) %}
            <div class="ticket-actions">
                {% if is_granted('TICKET_UPDATE_STATUS', ticket) %}
                    {{ include('tickets/_update_status.html.twig') }}
                {% endif %}
                {% if is_granted('TICKET_DELETE', ticket) %}
                    {{ include('tickets/_delete_form.html.twig') }}
                {% endif %}
            </div>
        {% endif %}
        
    </div>

    {# Lightbox pour agrandir les images #}
    <div id="image-lightbox" class="lightbox">
        <span class="lightbox-close">&times;</span>
        <img id="lightbox-image" class="lightbox-content" src="" alt="">
    </div>
{% endblock %}